In [2]:
import pandas as pd
import numpy as np

In [7]:
path_1= '../raw_data/230911_Hate_Speech_Classification_01.csv'
data_1 = pd.read_csv(path_1, encoding='latin-1')
data_1

       Unnamed: 0                                            comment label
0               1                                dalits are lowlives     1
1               2             gay people are a burden to our society     1
2               3                              Arabs are not welcome     1
3               4  I'm not saying we should actually eliminate he...     1
4               5                       bananas are for black people     1
...           ...                                                ...   ...
41139      117100                     Indian culture is so backwards     1
41140      118100  Women don't want equality, they just want to b...     1
41141      119100                                         fuck covid     0
41142        1205                           This computer is garbage     0
41143      121100                 The only good Muslim is a dead one     1

[41144 rows x 3 columns]

In [5]:
! ls

Iris Notebook.ipynb Marianne.ipynb      __init__.py         test_lua.ipynb

In [3]:
new_column_data = 'Hate_Speech_Classification_01'
new_column_name = 'source'

# Utilisez la méthode "insert" pour ajouter la nouvelle colonne à la position souhaitée (dans cet exemple, à la position 0)
data_1.insert(0, new_column_name, new_column_data)

data_1

,source,Unnamed: 0,comment,label
0,Hate_Speech_Classification_01,1,dalits are lowlives,1
1,Hate_Speech_Classification_01,2,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,3,Arabs are not welcome,1
3,Hate_Speech_Classification_01,4,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,5,bananas are for black people,1
...,...,...,...,...
41139,Hate_Speech_Classification_01,117100,Indian culture is so backwards,1
41140,Hate_Speech_Classification_01,118100,"Women don't want equality, they just want to b...",1
41141,Hate_Speech_Classification_01,119100,fuck covid,0
41142,Hate_Speech_Classification_01,1205,This computer is garbage,0
41143,Hate_Speech_Classification_01,121100,The only good Muslim is a dead one,1

In [4]:
selected_features=['source', 'comment','label']
data_1 = data_1[selected_features].copy()
data_1

,source,comment,label
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
41139,Hate_Speech_Classification_01,Indian culture is so backwards,1
41140,Hate_Speech_Classification_01,"Women don't want equality, they just want to b...",1
41141,Hate_Speech_Classification_01,fuck covid,0
41142,Hate_Speech_Classification_01,This computer is garbage,0
41143,Hate_Speech_Classification_01,The only good Muslim is a dead one,1

In [5]:
data_1 = data_1.rename(columns={'comment': 'text'})
data_1 = data_1.rename(columns={'label': 'offensive'})
data_1

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
41139,Hate_Speech_Classification_01,Indian culture is so backwards,1
41140,Hate_Speech_Classification_01,"Women don't want equality, they just want to b...",1
41141,Hate_Speech_Classification_01,fuck covid,0
41142,Hate_Speech_Classification_01,This computer is garbage,0
41143,Hate_Speech_Classification_01,The only good Muslim is a dead one,1

In [6]:
path_2= '/Users/irismarechal/Desktop/Le Wagon/moder_AI/230911_Hate_Speech_and_Offensive_Language_01.csv'
data_2 = pd.read_csv(path_2)
data_2

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
0,0,3,0,0,3,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,1,3,0,3,0,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,2,3,0,3,0,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,3,3,0,2,1,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,4,6,0,6,0,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...,...,...,...,...
24778,25291,3,0,2,1,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,25292,3,0,1,2,2,"you've gone and broke the wrong heart baby, an..."
24780,25294,3,0,3,0,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,25295,6,0,6,0,1,youu got wild bitches tellin you lies
24782,25296,3,0,0,3,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [7]:
selected_features=['class','tweet']
data_2 = data_2[selected_features].copy()
data_2

       class                                              tweet
0          2  !!! RT @mayasolovely: As a woman you shouldn't...
1          1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2          1  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3          1  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4          1  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...      ...                                                ...
24778      1  you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779      2  you've gone and broke the wrong heart baby, an...
24780      1  young buck wanna eat!!.. dat nigguh like I ain...
24781      1              youu got wild bitches tellin you lies
24782      2  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

[24783 rows x 2 columns]

In [8]:
new_column_data = 'Hate_Speech_and_Offensive_Language'
new_column_name = 'source'

# Utilisez la méthode "insert" pour ajouter la nouvelle colonne à la position souhaitée (dans cet exemple, à la position 0)
data_2.insert(0, new_column_name, new_column_data)

data_2

,source,class,tweet
0,Hate_Speech_and_Offensive_Language,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,Hate_Speech_and_Offensive_Language,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,Hate_Speech_and_Offensive_Language,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,Hate_Speech_and_Offensive_Language,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,Hate_Speech_and_Offensive_Language,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,Hate_Speech_and_Offensive_Language,2,"you've gone and broke the wrong heart baby, an..."
24780,Hate_Speech_and_Offensive_Language,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,Hate_Speech_and_Offensive_Language,1,youu got wild bitches tellin you lies
24782,Hate_Speech_and_Offensive_Language,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [9]:
data_2 = data_2.rename(columns={'class': 'offensive'})
data_2 = data_2.rename(columns={'tweet': 'text'})
data_2

,source,offensive,text
0,Hate_Speech_and_Offensive_Language,2,!!! RT @mayasolovely: As a woman you shouldn't...
1,Hate_Speech_and_Offensive_Language,1,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2,Hate_Speech_and_Offensive_Language,1,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3,Hate_Speech_and_Offensive_Language,1,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4,Hate_Speech_and_Offensive_Language,1,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,1,you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779,Hate_Speech_and_Offensive_Language,2,"you've gone and broke the wrong heart baby, an..."
24780,Hate_Speech_and_Offensive_Language,1,young buck wanna eat!!.. dat nigguh like I ain...
24781,Hate_Speech_and_Offensive_Language,1,youu got wild bitches tellin you lies
24782,Hate_Speech_and_Offensive_Language,2,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...

In [10]:
data_2 = data_2[['source', 'text', 'offensive']]
data_2

,source,text,offensive
0,Hate_Speech_and_Offensive_Language,!!! RT @mayasolovely: As a woman you shouldn't...,2
1,Hate_Speech_and_Offensive_Language,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,1
2,Hate_Speech_and_Offensive_Language,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,1
3,Hate_Speech_and_Offensive_Language,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,1
4,Hate_Speech_and_Offensive_Language,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,1
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,1
24779,Hate_Speech_and_Offensive_Language,"you've gone and broke the wrong heart baby, an...",2
24780,Hate_Speech_and_Offensive_Language,young buck wanna eat!!.. dat nigguh like I ain...,1
24781,Hate_Speech_and_Offensive_Language,youu got wild bitches tellin you lies,1
24782,Hate_Speech_and_Offensive_Language,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,2

In [11]:
data_2['offensive'] = data_2['offensive'].replace({0: 1, 1: 1, 2:0})
data_2

,source,text,offensive
0,Hate_Speech_and_Offensive_Language,!!! RT @mayasolovely: As a woman you shouldn't...,0
1,Hate_Speech_and_Offensive_Language,!!!!! RT @mleew17: boy dats cold...tyga dwn ba...,1
2,Hate_Speech_and_Offensive_Language,!!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...,1
3,Hate_Speech_and_Offensive_Language,!!!!!!!!! RT @C_G_Anderson: @viva_based she lo...,1
4,Hate_Speech_and_Offensive_Language,!!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...,1
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,1
24779,Hate_Speech_and_Offensive_Language,"you've gone and broke the wrong heart baby, an...",0
24780,Hate_Speech_and_Offensive_Language,young buck wanna eat!!.. dat nigguh like I ain...,1
24781,Hate_Speech_and_Offensive_Language,youu got wild bitches tellin you lies,1
24782,Hate_Speech_and_Offensive_Language,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,0

In [12]:
concatenated_df_1= pd.concat([data_1, data_2])
concatenated_df_1

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,1
24779,Hate_Speech_and_Offensive_Language,"you've gone and broke the wrong heart baby, an...",0
24780,Hate_Speech_and_Offensive_Language,young buck wanna eat!!.. dat nigguh like I ain...,1
24781,Hate_Speech_and_Offensive_Language,youu got wild bitches tellin you lies,1
24782,Hate_Speech_and_Offensive_Language,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,0

In [13]:
valeurs_uniques = concatenated_df_1['offensive'].unique()
valeurs_uniques

array(['1', '0', 'O', 0, 1], dtype=object)

In [14]:
concatenated_df_1['offensive'] = concatenated_df_1['offensive'].replace({'O':0})
concatenated_df_1['offensive']=concatenated_df_1['offensive'].astype(int)


valeurs_uniques = concatenated_df_1['offensive'].unique()
valeurs_uniques

concatenated_df_1

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
24778,Hate_Speech_and_Offensive_Language,you's a muthaf***in lie &#8220;@LifeAsKing: @2...,1
24779,Hate_Speech_and_Offensive_Language,"you've gone and broke the wrong heart baby, an...",0
24780,Hate_Speech_and_Offensive_Language,young buck wanna eat!!.. dat nigguh like I ain...,1
24781,Hate_Speech_and_Offensive_Language,youu got wild bitches tellin you lies,1
24782,Hate_Speech_and_Offensive_Language,~~Ruffled | Ntac Eileen Dahlia - Beautiful col...,0

In [15]:
#retrieve file
file_path = "/Users/irismarechal/Desktop/Le Wagon/moder_AI/230911_Dynamically_Generated_Hate_Speech_01.csv"
hatespeech = pd.read_csv(file_path)

hatespeech["source"]="230911_Dynamically_Generated_Hate_Speech_01" # add source of the doc 
hatespeech = hatespeech[["source", "text", "label"]] #select columns 
hatespeech.rename(columns={'label':'offensive'}, inplace=True) # rename column 
#encore offensive column
mapping = {'hate': 1, 'nothate': '0'} 

hatespeech["offensive"] = hatespeech["offensive"].map(mapping)

hatespeech

,source,text,offensive
0,230911_Dynamically_Generated_Hate_Speech_01,It should be legal for a husband to rape his wife,1
1,230911_Dynamically_Generated_Hate_Speech_01,dalits are lowlife scum,1
2,230911_Dynamically_Generated_Hate_Speech_01,dalits are lowlives,1
3,230911_Dynamically_Generated_Hate_Speech_01,It was a better world when women dare not ques...,1
4,230911_Dynamically_Generated_Hate_Speech_01,I don't work this hard so that those immigrant...,1
...,...,...,...
40618,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the foreigners f...,1
40619,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the immigrants f...,1
40620,230911_Dynamically_Generated_Hate_Speech_01,dalits are unworthy of the Gods love,1
40621,230911_Dynamically_Generated_Hate_Speech_01,dalits are worthless,1
40622,230911_Dynamically_Generated_Hate_Speech_01,dalits are deserves to be treated as lowlife,1

In [16]:
concatenated_df_2= pd.concat([concatenated_df_1, hatespeech])
concatenated_df_2

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
40618,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the foreigners f...,1
40619,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the immigrants f...,1
40620,230911_Dynamically_Generated_Hate_Speech_01,dalits are unworthy of the Gods love,1
40621,230911_Dynamically_Generated_Hate_Speech_01,dalits are worthless,1
40622,230911_Dynamically_Generated_Hate_Speech_01,dalits are deserves to be treated as lowlife,1

In [17]:
concatenated_df_2.describe()

                               source                      text  offensive
count                          106550                    106550     106550
unique                              3                     83248          3
top     Hate_Speech_Classification_01  Blacks are such pondlife          1
freq                            41144                        11      64902

In [18]:
concatenated_df_2['offensive']=concatenated_df_2['offensive'].astype(int)
concatenated_df_2

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
40618,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the foreigners f...,1
40619,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the immigrants f...,1
40620,230911_Dynamically_Generated_Hate_Speech_01,dalits are unworthy of the Gods love,1
40621,230911_Dynamically_Generated_Hate_Speech_01,dalits are worthless,1
40622,230911_Dynamically_Generated_Hate_Speech_01,dalits are deserves to be treated as lowlife,1

In [19]:
concatenated_df_3=concatenated_df_2.reset_index(drop=True)
concatenated_df_3

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
106545,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the foreigners f...,1
106546,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the immigrants f...,1
106547,230911_Dynamically_Generated_Hate_Speech_01,dalits are unworthy of the Gods love,1
106548,230911_Dynamically_Generated_Hate_Speech_01,dalits are worthless,1
106549,230911_Dynamically_Generated_Hate_Speech_01,dalits are deserves to be treated as lowlife,1

In [20]:
concatenated_df_3

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
106545,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the foreigners f...,1
106546,230911_Dynamically_Generated_Hate_Speech_01,we should forcibly remove all the immigrants f...,1
106547,230911_Dynamically_Generated_Hate_Speech_01,dalits are unworthy of the Gods love,1
106548,230911_Dynamically_Generated_Hate_Speech_01,dalits are worthless,1
106549,230911_Dynamically_Generated_Hate_Speech_01,dalits are deserves to be treated as lowlife,1

In [21]:
concatenated_df_3=concatenated_df_2[~concatenated_df_2[['text','offensive']].duplicated()]
concatenated_df_3=concatenated_df_3.reset_index(drop=True)
concatenated_df_3

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
83259,230911_Dynamically_Generated_Hate_Speech_01,White men can't fight if their life depended o...,1
83260,230911_Dynamically_Generated_Hate_Speech_01,white people are good for nothing,1
83261,230911_Dynamically_Generated_Hate_Speech_01,Gay men hate women,1
83262,230911_Dynamically_Generated_Hate_Speech_01,A husband should be allowed to do whatever he ...,1
83263,230911_Dynamically_Generated_Hate_Speech_01,Women are hateful,1

In [22]:
hateXplain = pd.read_json("/Users/irismarechal/Desktop/Le Wagon/moder_AI/230911_HateXplain.json")

hateXplain_inversed = hateXplain.transpose()

hateXplain=hateXplain_inversed


hateXplain["source"]="230911_HateXplain" # add source of the doc


hateXplain = hateXplain[["post_tokens", "annotators", "source"]].copy()

hateXplain.reset_index(inplace=True, drop=True)

hateXplain["offensive"]=0

hateXplain["offensive"]=hateXplain["annotators"].apply(lambda x:x[0]["label"]).apply(lambda x:0 if x =="normal" else 1)
hateXplain["offensive"]

hateXplain

,post_tokens,annotators,source,offensive
0,"[i, dont, think, im, getting, my, baby, them, ...","[{'label': 'normal', 'annotator_id': 1, 'targe...",230911_HateXplain,0
1,"[we, cannot, continue, calling, ourselves, fem...","[{'label': 'normal', 'annotator_id': 1, 'targe...",230911_HateXplain,0
2,"[nawt, yall, niggers, ignoring, me]","[{'label': 'normal', 'annotator_id': 4, 'targe...",230911_HateXplain,0
3,"[<user>, i, am, bit, confused, coz, chinese, p...","[{'label': 'hatespeech', 'annotator_id': 1, 't...",230911_HateXplain,1
4,"[this, bitch, in, whataburger, eating, a, burg...","[{'label': 'hatespeech', 'annotator_id': 4, 't...",230911_HateXplain,1
...,...,...,...,...
20143,"[if, ur, still, on, twitter, tell, carlton, i,...","[{'label': 'offensive', 'annotator_id': 217, '...",230911_HateXplain,1
20144,"[when, i, first, got, on, here, and, said, i, ...","[{'label': 'offensive', 'annotator_id': 220, '...",230911_HateXplain,1
20145,"[was, macht, der, moslem, wenn, der, zion, geg...","[{'label': 'offensive', 'annotator_id': 206, '...",230911_HateXplain,1
20146,"[it, is, awful, look, at, world, demographics,...","[{'label': 'hatespeech', 'annotator_id': 209, ...",230911_HateXplain,1
20147,"[the, jewish, globalist, elite, have, only, im...","[{'label': 'hatespeech', 'annotator_id': 200, ...",230911_HateXplain,1

In [23]:
hateXplain = hateXplain.rename(columns={'post_tokens': 'text'})
hateXplain

,text,annotators,source,offensive
0,"[i, dont, think, im, getting, my, baby, them, ...","[{'label': 'normal', 'annotator_id': 1, 'targe...",230911_HateXplain,0
1,"[we, cannot, continue, calling, ourselves, fem...","[{'label': 'normal', 'annotator_id': 1, 'targe...",230911_HateXplain,0
2,"[nawt, yall, niggers, ignoring, me]","[{'label': 'normal', 'annotator_id': 4, 'targe...",230911_HateXplain,0
3,"[<user>, i, am, bit, confused, coz, chinese, p...","[{'label': 'hatespeech', 'annotator_id': 1, 't...",230911_HateXplain,1
4,"[this, bitch, in, whataburger, eating, a, burg...","[{'label': 'hatespeech', 'annotator_id': 4, 't...",230911_HateXplain,1
...,...,...,...,...
20143,"[if, ur, still, on, twitter, tell, carlton, i,...","[{'label': 'offensive', 'annotator_id': 217, '...",230911_HateXplain,1
20144,"[when, i, first, got, on, here, and, said, i, ...","[{'label': 'offensive', 'annotator_id': 220, '...",230911_HateXplain,1
20145,"[was, macht, der, moslem, wenn, der, zion, geg...","[{'label': 'offensive', 'annotator_id': 206, '...",230911_HateXplain,1
20146,"[it, is, awful, look, at, world, demographics,...","[{'label': 'hatespeech', 'annotator_id': 209, ...",230911_HateXplain,1
20147,"[the, jewish, globalist, elite, have, only, im...","[{'label': 'hatespeech', 'annotator_id': 200, ...",230911_HateXplain,1

In [24]:
hateXplain = hateXplain[['source', 'text', 'offensive']].copy()
hateXplain

,source,text,offensive
0,230911_HateXplain,"[i, dont, think, im, getting, my, baby, them, ...",0
1,230911_HateXplain,"[we, cannot, continue, calling, ourselves, fem...",0
2,230911_HateXplain,"[nawt, yall, niggers, ignoring, me]",0
3,230911_HateXplain,"[<user>, i, am, bit, confused, coz, chinese, p...",1
4,230911_HateXplain,"[this, bitch, in, whataburger, eating, a, burg...",1
...,...,...,...
20143,230911_HateXplain,"[if, ur, still, on, twitter, tell, carlton, i,...",1
20144,230911_HateXplain,"[when, i, first, got, on, here, and, said, i, ...",1
20145,230911_HateXplain,"[was, macht, der, moslem, wenn, der, zion, geg...",1
20146,230911_HateXplain,"[it, is, awful, look, at, world, demographics,...",1
20147,230911_HateXplain,"[the, jewish, globalist, elite, have, only, im...",1

In [25]:
hateXplain['text']=hateXplain['text'].astype(str)
hateXplain['text']=hateXplain['text'].str.replace("'", "").str.replace(",", "").str.strip()

hateXplain

,source,text,offensive
0,230911_HateXplain,[i dont think im getting my baby them white 9 ...,0
1,230911_HateXplain,[we cannot continue calling ourselves feminist...,0
2,230911_HateXplain,[nawt yall niggers ignoring me],0
3,230911_HateXplain,[<user> i am bit confused coz chinese ppl can ...,1
4,230911_HateXplain,[this bitch in whataburger eating a burger wit...,1
...,...,...,...
20143,230911_HateXplain,[if ur still on twitter tell carlton i said hi...,1
20144,230911_HateXplain,[when i first got on here and said i hate trum...,1
20145,230911_HateXplain,[was macht der moslem wenn der zion gegen sein...,1
20146,230911_HateXplain,[it is awful look at world demographics asians...,1
20147,230911_HateXplain,[the jewish globalist elite have only imported...,1

In [26]:
concatenated_df_4= pd.concat([concatenated_df_3, hateXplain])
concatenated_df_4

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
20143,230911_HateXplain,[if ur still on twitter tell carlton i said hi...,1
20144,230911_HateXplain,[when i first got on here and said i hate trum...,1
20145,230911_HateXplain,[was macht der moslem wenn der zion gegen sein...,1
20146,230911_HateXplain,[it is awful look at world demographics asians...,1
20147,230911_HateXplain,[the jewish globalist elite have only imported...,1

In [27]:
concatenated_df_4=concatenated_df_4[~concatenated_df_4[['text','offensive']].duplicated()]
concatenated_df_4=concatenated_df_4.reset_index(drop=True)
concatenated_df_4

,source,text,offensive
0,Hate_Speech_Classification_01,dalits are lowlives,1
1,Hate_Speech_Classification_01,gay people are a burden to our society,1
2,Hate_Speech_Classification_01,Arabs are not welcome,1
3,Hate_Speech_Classification_01,I'm not saying we should actually eliminate he...,1
4,Hate_Speech_Classification_01,bananas are for black people,1
...,...,...,...
103376,230911_HateXplain,[if ur still on twitter tell carlton i said hi...,1
103377,230911_HateXplain,[when i first got on here and said i hate trum...,1
103378,230911_HateXplain,[was macht der moslem wenn der zion gegen sein...,1
103379,230911_HateXplain,[it is awful look at world demographics asians...,1
103380,230911_HateXplain,[the jewish globalist elite have only imported...,1

In [28]:
concatenated_df_4.to_csv("/Users/irismarechal/Desktop/Le Wagon/moder_AI/clean_dataset_v2.csv", index=False)