# Clean data

In [16]:
import pandas as pd
from moder_ia.functions import cleaning_table, cleaning_text

In [17]:
data = pd.read_csv('/home/luades/code/irismarechal1997/moder_ia/raw_data/230911_Dynamically_Generated_Hate_Speech_01.csv')
data

,Unnamed: 0,id,text,label,type,model_wrong,db.model_preds,status,round,split,annotator
0,1,10000,It should be legal for a husband to rape his wife,hate,notgiven,True,0.97457,dynabench entry,1,train,gnzuctwed3
1,2,10001,dalits are lowlife scum,hate,notgiven,False,0.08233,dynabench entry,1,test,cagnluiznm
2,3,10002,dalits are lowlives,hate,notgiven,True,0.92319,dynabench entry,1,train,cagnluiznm
3,4,10003,It was a better world when women dare not ques...,hate,notgiven,True,0.99006,dynabench entry,1,test,gnzuctwed3
4,5,10004,I don't work this hard so that those immigrant...,hate,notgiven,True,0.98836,dynabench entry,1,train,cagnluiznm
...,...,...,...,...,...,...,...,...,...,...,...
40618,40736,9995,we should forcibly remove all the foreigners f...,hate,notgiven,True,0.86945,dynabench entry,1,train,cagnluiznm
40619,40737,9996,we should forcibly remove all the immigrants f...,hate,notgiven,True,0.50039,dynabench entry,1,train,cagnluiznm
40620,40738,9997,dalits are unworthy of the Gods love,hate,notgiven,True,0.97652,dynabench entry,1,train,cagnluiznm
40621,40739,9998,dalits are worthless,hate,notgiven,True,0.94326,dynabench entry,1,train,cagnluiznm
40622,40740,9999,dalits are deserves to be treated as lowlife,hate,notgiven,True,0.94324,dynabench entry,1,train,cagnluiznm

In [18]:
data = data[['text','label']]
data

                                                    text label
0      It should be legal for a husband to rape his wife  hate
1                                dalits are lowlife scum  hate
2                                    dalits are lowlives  hate
3      It was a better world when women dare not ques...  hate
4      I don't work this hard so that those immigrant...  hate
...                                                  ...   ...
40618  we should forcibly remove all the foreigners f...  hate
40619  we should forcibly remove all the immigrants f...  hate
40620               dalits are unworthy of the Gods love  hate
40621                               dalits are worthless  hate
40622       dalits are deserves to be treated as lowlife  hate

[40623 rows x 2 columns]

In [19]:
len(data)

40623

In [20]:
# remove duplicates

#before removing
len(data) # Check number of rows before removing duplicates
data.duplicated() # Check whether a row is a duplicated version of a previous row
data.duplicated().sum() # Compute the number of duplicated rows

157

In [21]:
#after removing
data = data.drop_duplicates() # Remove duplicates
len(data)# Check new number of rows

40466

In [22]:
# check missing data

# Counting the number of NaN for each column
data.isnull().sum().sort_values(ascending=False)

text     0
label    0
dtype: int64

In [35]:
# Decide what to do with missing value

# Option 1: Drop rows where  value is missing
data = data.dropna(subset=['label']) 
data

                                                    text label
0      It should be legal for a husband to rape his wife  hate
1                                dalits are lowlife scum  hate
2                                    dalits are lowlives  hate
3      It was a better world when women dare not ques...  hate
4      I don't work this hard so that those immigrant...  hate
...                                                  ...   ...
40618  we should forcibly remove all the foreigners f...  hate
40619  we should forcibly remove all the immigrants f...  hate
40620               dalits are unworthy of the Gods love  hate
40621                               dalits are worthless  hate
40622       dalits are deserves to be treated as lowlife  hate

[40466 rows x 2 columns]

In [39]:
data.loc[:, 'text']

0        It should be legal for a husband to rape his wife
1                                  dalits are lowlife scum
2                                      dalits are lowlives
3        It was a better world when women dare not ques...
4        I don't work this hard so that those immigrant...
                               ...
40618    we should forcibly remove all the foreigners f...
40619    we should forcibly remove all the immigrants f...
40620                 dalits are unworthy of the Gods love
40621                                 dalits are worthless
40622         dalits are deserves to be treated as lowlife
Name: text, Length: 40466, dtype: object

In [ ]:
# balancing